use mklyu126;

-- USER TABLE
DROP TABLE IF EXISTS USER;
CREATE TABLE USER (
Email VARCHAR(255) PRIMARY KEY,
DateAdded DateTime DEFAULT CURRENT_TIMESTAMP,
NickName VARCHAR(255) UNIQUE NULL,
Profile VARCHAR(255) NULL
);

-- BOOK TABLE
DROP TABLE IF EXISTS BOOK;
CREATE TABLE BOOK (
BookID INT PRIMARY KEY AUTO_INCREMENT,
Title VARCHAR(255),
Year INT(4),
NumRaters INT DEFAULT 0,
Rating DECIMAL(2, 1)
);

-- AUTHOR TABLE
DROP TABLE IF EXISTS AUTHOR;
CREATE TABLE AUTHOR(
AuthorID INT PRIMARY KEY AUTO_INCREMENT,
LastName VARCHAR(255) NULL,
FirstName VARCHAR(255),
MiddleName VARCHAR(255) NULL
);

-- BOOKAUTHOR TABLE
DROP TABLE IF EXISTS BOOKAUTHOR;
CREATE TABLE BOOKAUTHOR(
AuthorID INT,
BookID INT,
PRIMARY KEY (AuthorID, BookID),
FOREIGN KEY (AuthorID) REFERENCES AUTHOR(AuthorID),
FOREIGN KEY (BookID) REFERENCES BOOK(BookID)
);

-- READBOOK TABLE
DROP TABLE IF EXISTS READBOOK;
CREATE TABLE READBOOK(
BookID INT,
Email VARCHAR(255),
DateRead Date,
Rating INT CHECK (Rating BETWEEN 1 and 10),
PRIMARY KEY (BookID, Email),
FOREIGN KEY (BookID) REFERENCES BOOK(BookID),
FOREIGN KEY (Email) REFERENCES USER(Email)
);